apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: focalboard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: focalboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: focalboard
  template:
    metadata:
      labels:
        app: focalboard
    spec:
      containers:
        - name: focalboard
          image: focalboard
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /opt/focalboard/data
              name: focalboard
      volumes:
        - name: focalboard
          persistentVolumeClaim:
            claimName: focalboard
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: focalboard
  name: focalboard
spec:
  ports:
    - port: 8080
      nodePort: 30088
  selector:
    app: focalboard
  type: NodePort
