
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dashy
  namespace: dashy
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashy
  namespace: dashy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashy
  template:
    metadata:
      labels:
        app: dashy
    spec:
      containers:
      - name: dashy
        image: lissy93/dashy:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /app/public/conf.yml
          name: dashy
          subPath: conf.yml
      volumes:
      - name: dashy
        persistentVolumeClaim:
          claimName: dashy
---
apiVersion: v1
kind: Service
metadata:
  name: dashy
  namespace: dashy
spec:
  ports:
  - port: 80
    nodePort: 30003
  selector:
    app: dashy
  type: NodePort
